// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockWhatsAppService is an autogenerated mock type for the WhatsAppService type
type MockWhatsAppService struct {
	mock.Mock
}

type MockWhatsAppService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockWhatsAppService) EXPECT() *MockWhatsAppService_Expecter {
	return &MockWhatsAppService_Expecter{mock: &_m.Mock}
}

// GetQRCode provides a mock function with no fields
func (_m *MockWhatsAppService) GetQRCode() (string, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetQRCode")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func() (string, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockWhatsAppService_GetQRCode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetQRCode'
type MockWhatsAppService_GetQRCode_Call struct {
	*mock.Call
}

// GetQRCode is a helper method to define mock.On call
func (_e *MockWhatsAppService_Expecter) GetQRCode() *MockWhatsAppService_GetQRCode_Call {
	return &MockWhatsAppService_GetQRCode_Call{Call: _e.mock.On("GetQRCode")}
}

func (_c *MockWhatsAppService_GetQRCode_Call) Run(run func()) *MockWhatsAppService_GetQRCode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockWhatsAppService_GetQRCode_Call) Return(_a0 string, _a1 error) *MockWhatsAppService_GetQRCode_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockWhatsAppService_GetQRCode_Call) RunAndReturn(run func() (string, error)) *MockWhatsAppService_GetQRCode_Call {
	_c.Call.Return(run)
	return _c
}

// IsConnected provides a mock function with no fields
func (_m *MockWhatsAppService) IsConnected() bool {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for IsConnected")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// MockWhatsAppService_IsConnected_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsConnected'
type MockWhatsAppService_IsConnected_Call struct {
	*mock.Call
}

// IsConnected is a helper method to define mock.On call
func (_e *MockWhatsAppService_Expecter) IsConnected() *MockWhatsAppService_IsConnected_Call {
	return &MockWhatsAppService_IsConnected_Call{Call: _e.mock.On("IsConnected")}
}

func (_c *MockWhatsAppService_IsConnected_Call) Run(run func()) *MockWhatsAppService_IsConnected_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockWhatsAppService_IsConnected_Call) Return(_a0 bool) *MockWhatsAppService_IsConnected_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockWhatsAppService_IsConnected_Call) RunAndReturn(run func() bool) *MockWhatsAppService_IsConnected_Call {
	_c.Call.Return(run)
	return _c
}

// Logout provides a mock function with no fields
func (_m *MockWhatsAppService) Logout() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Logout")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockWhatsAppService_Logout_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Logout'
type MockWhatsAppService_Logout_Call struct {
	*mock.Call
}

// Logout is a helper method to define mock.On call
func (_e *MockWhatsAppService_Expecter) Logout() *MockWhatsAppService_Logout_Call {
	return &MockWhatsAppService_Logout_Call{Call: _e.mock.On("Logout")}
}

func (_c *MockWhatsAppService_Logout_Call) Run(run func()) *MockWhatsAppService_Logout_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockWhatsAppService_Logout_Call) Return(_a0 error) *MockWhatsAppService_Logout_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockWhatsAppService_Logout_Call) RunAndReturn(run func() error) *MockWhatsAppService_Logout_Call {
	_c.Call.Return(run)
	return _c
}

// SendMessage provides a mock function with given fields: ctx, phone, message
func (_m *MockWhatsAppService) SendMessage(ctx context.Context, phone string, message string) error {
	ret := _m.Called(ctx, phone, message)

	if len(ret) == 0 {
		panic("no return value specified for SendMessage")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, phone, message)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockWhatsAppService_SendMessage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendMessage'
type MockWhatsAppService_SendMessage_Call struct {
	*mock.Call
}

// SendMessage is a helper method to define mock.On call
//   - ctx context.Context
//   - phone string
//   - message string
func (_e *MockWhatsAppService_Expecter) SendMessage(ctx interface{}, phone interface{}, message interface{}) *MockWhatsAppService_SendMessage_Call {
	return &MockWhatsAppService_SendMessage_Call{Call: _e.mock.On("SendMessage", ctx, phone, message)}
}

func (_c *MockWhatsAppService_SendMessage_Call) Run(run func(ctx context.Context, phone string, message string)) *MockWhatsAppService_SendMessage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockWhatsAppService_SendMessage_Call) Return(_a0 error) *MockWhatsAppService_SendMessage_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockWhatsAppService_SendMessage_Call) RunAndReturn(run func(context.Context, string, string) error) *MockWhatsAppService_SendMessage_Call {
	_c.Call.Return(run)
	return _c
}

// Start provides a mock function with given fields: ctx
func (_m *MockWhatsAppService) Start(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Start")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockWhatsAppService_Start_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Start'
type MockWhatsAppService_Start_Call struct {
	*mock.Call
}

// Start is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockWhatsAppService_Expecter) Start(ctx interface{}) *MockWhatsAppService_Start_Call {
	return &MockWhatsAppService_Start_Call{Call: _e.mock.On("Start", ctx)}
}

func (_c *MockWhatsAppService_Start_Call) Run(run func(ctx context.Context)) *MockWhatsAppService_Start_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockWhatsAppService_Start_Call) Return(_a0 error) *MockWhatsAppService_Start_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockWhatsAppService_Start_Call) RunAndReturn(run func(context.Context) error) *MockWhatsAppService_Start_Call {
	_c.Call.Return(run)
	return _c
}

// Stop provides a mock function with no fields
func (_m *MockWhatsAppService) Stop() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Stop")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockWhatsAppService_Stop_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Stop'
type MockWhatsAppService_Stop_Call struct {
	*mock.Call
}

// Stop is a helper method to define mock.On call
func (_e *MockWhatsAppService_Expecter) Stop() *MockWhatsAppService_Stop_Call {
	return &MockWhatsAppService_Stop_Call{Call: _e.mock.On("Stop")}
}

func (_c *MockWhatsAppService_Stop_Call) Run(run func()) *MockWhatsAppService_Stop_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockWhatsAppService_Stop_Call) Return(_a0 error) *MockWhatsAppService_Stop_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockWhatsAppService_Stop_Call) RunAndReturn(run func() error) *MockWhatsAppService_Stop_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockWhatsAppService creates a new instance of MockWhatsAppService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockWhatsAppService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockWhatsAppService {
	mock := &MockWhatsAppService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
