// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockWorkflowConfigRepository is an autogenerated mock type for the WorkflowConfigRepository type
type MockWorkflowConfigRepository struct {
	mock.Mock
}

type MockWorkflowConfigRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockWorkflowConfigRepository) EXPECT() *MockWorkflowConfigRepository_Expecter {
	return &MockWorkflowConfigRepository_Expecter{mock: &_m.Mock}
}

// GetActiveWorkflowType provides a mock function with given fields: ctx
func (_m *MockWorkflowConfigRepository) GetActiveWorkflowType(ctx context.Context) (string, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetActiveWorkflowType")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (string, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) string); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockWorkflowConfigRepository_GetActiveWorkflowType_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetActiveWorkflowType'
type MockWorkflowConfigRepository_GetActiveWorkflowType_Call struct {
	*mock.Call
}

// GetActiveWorkflowType is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockWorkflowConfigRepository_Expecter) GetActiveWorkflowType(ctx interface{}) *MockWorkflowConfigRepository_GetActiveWorkflowType_Call {
	return &MockWorkflowConfigRepository_GetActiveWorkflowType_Call{Call: _e.mock.On("GetActiveWorkflowType", ctx)}
}

func (_c *MockWorkflowConfigRepository_GetActiveWorkflowType_Call) Run(run func(ctx context.Context)) *MockWorkflowConfigRepository_GetActiveWorkflowType_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockWorkflowConfigRepository_GetActiveWorkflowType_Call) Return(_a0 string, _a1 error) *MockWorkflowConfigRepository_GetActiveWorkflowType_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockWorkflowConfigRepository_GetActiveWorkflowType_Call) RunAndReturn(run func(context.Context) (string, error)) *MockWorkflowConfigRepository_GetActiveWorkflowType_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockWorkflowConfigRepository creates a new instance of MockWorkflowConfigRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockWorkflowConfigRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockWorkflowConfigRepository {
	mock := &MockWorkflowConfigRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
